# Generated by Django 4.0.4 on 2022-05-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='new_projects/')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('suminvest', models.IntegerField()),
                ('operatingbusiness', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('numberworker', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('businesstype', models.CharField(choices=[('STARTUP', 'Startup'), ('FRANCHISE', 'Franchise'), ('READYBUSINESS', 'Ready Business')], max_length=15)),
            ],
            options={
                'verbose_name': 'Yangi Loyiha',
                'verbose_name_plural': 'Yangi Loyihalar',
            },
        ),
    ]
